# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "xiashiwuming"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily-1.json'
json_gitpage_path: './docs/cv-arxiv-daily-1-web.json'
json_wechat_path: './docs/cv-arxiv-daily-1-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Schodinger": 
        filters: ["Schodinger", "mobility edge"]
    "anderson":
        filters: ["anderson", "Localization"]
   
